### ISSUE TITLE
用户信息的录入&问题

### ISSUE THREAD

**Issue by PersuesJohnson** [ritou11/CLMS-SigmaGo#10]
@thuallen 现在爬虫能爬下网络学堂的课程信息和学生部分个人信息（info还在和它的cookie斗争中...）现在的数据库中用户的表内容较简略，搜索策略所需要的信息可以直接在用户的类中修改

@ritou11 爬虫需要用户的学号和密码，前端需要确定这一信息在什么时候可以获取得到

**Comment by ritou11** [comment]
前端应该设置一个个人中心，这个还没写，直接写在个人中心里，前端给后端发学堂的明文密码（有点脏😳）
