### ISSUE TITLE
关于推荐

### ISSUE THREAD

**Issue by thuallen** [ritou11/CLMS-SigmaGo#11]
现在想到的推荐机制：
step1 搜索举办方为本院系的比赛与讲座。（需要知道院系，以及从holder里提取信息）
step2 搜索含有该用户的兴趣tag的比赛与讲座。（已添加用户tag，但现在好像没啥用的样子）
step3 搜索含有根据该用户院系，自动形成的tag 的比赛与讲座。（需要知道院系）
step3.5 删除举办时间与该用户课程有冲突的搜索结果。（需要知道课程时间）
step4 根据该用户年级，将前面两步搜索到的比赛、讲座分别排序。如大一大二优先推荐难度较低的比赛（从introduction里面提取或者单独设立比赛难度或者面向的对象会让这一步简单一点）,以及工具使用培训、编程语言培训类的讲座。（已经知道学生类型、年级，但还不知道如何从讲座和比赛中提取这一信息）
step5 将前面得到的排序结果返回给首页要显示的list.

**Comment by ritou11** [comment]
秀主席在现在的Main/recommend.py中给出了生成recommend_list的函数，这个函数可以视作推荐算法的接口。目前仅仅用了tag搜索的方法，下一步按照讨论的思路完成高级的实现。
