### ISSUE TITLE
微信端问题

### ISSUE THREAD

**Issue by zhang-zx** [ritou11/CLMS-SigmaGo#12]
model里面能不能有competition和lecture的url链接和小图网址，用来给微信返回

**Comment by ritou11** [comment]
image.url
详细参见[Django Document](https://docs.djangoproject.com/en/1.11/ref/models/fields/#django.db.models.FileField) 及前端代码: https://github.com/ritou11/CLMS-SigmaGo/blob/c035906dc902aef755e1a62fae9df7363bbb7cf2/src/CLMS/templates/index.html#L119

**Comment by huangxf14** [comment]
小图网址？是要我这边额外在数据库里存个缩略图么……或者看你能不能在调用的时候直接调一下width和height

**Comment by ritou11** [comment]
存个缩略图会好点吧？毕竟每次都发大图实在是太慢了伤不起啊😢

**Comment by huangxf14** [comment]
加了缩略图。需要用到skimage库，如果是用anaconda的话就不用管了，不是的话还得装一下。然后数据库里多了一个thumb就是缩略图。新的数据库在https://pan.baidu.com/s/1eStm54e
