### ISSUE TITLE
首页作者信息收集

### ISSUE THREAD

**Issue by ritou11** [ritou11/CLMS-SigmaGo#19]
@huangxf14 @thuallen @PersuesJohnson @zhang-zx @Rrrima 
## 大家在这回复自己的信息
* Duty
* Intro
* Github Page
* Weibo
## 在微信群里发
* 一个美照／帅照

**Comment by huangxf14** [comment]
Duty: send tea for dalao
Intro:I know nothing except BOP(Baidu Oriented Programming)
Github Page:github.com/huangxf14
Weibo:What's this?

**Comment by thuallen** [comment]
Duty: send coffee for dalaos
Intro: I may also know a little about GOP
Github Page:  github.com/thuallen
Weibo: Allen_Hanyz

**Comment by zhang-zx** [comment]
Duty: make phone calls for dalaos
Intro: I know also know a little about BOP
Github Page: github.com/zhang-zx
Weibo: I don't have one

**Comment by huangxf14** [comment]
Luka Johnson
Duty: drink tea,drink coffee and receive phone calls
Intro: Familiar with MOP(Mirror Oriented Programming)
Github Page: github.com/PersuesJohnson
Weibo:

**Comment by ritou11** [comment]
* Duty: Watch dalaos worshiping each other
* Intro:  I'm an expert in COP(Clipboard Oriented Programming)
* Github Page: github.com/ritou11
* Weibo: weibo.com/ritou11
* Wechat: ritou11

**Comment by Rrrima** [comment]
Duty: Dishwashing
Intro: Nothing but focus on SIP (Source Importing Programming)
Github Page: github.com/Rrrima
Weibo: /
Wechat: Vacuum2020
