### ISSUE TITLE
Bug汇总

### ISSUE THREAD

**Issue by PersuesJohnson** [ritou11/CLMS-SigmaGo#26]
* 主页登陆的时候没有失败提示
* 主页点击discover 未登录时在页面http://sigmago.nogeek.cn/recom/出现错误（pr中已解决）
* 搜索翻页bug（pr中已解决）
* usericon当没有的时候显示默认头像会出bug（pr中已解决，但是如果前端不要的话直接在personalinfo中改前端就好了）
* search中如果没有任何关键词会返回错误（pr中已解决）

**Comment by ritou11** [comment]
各个页面的header不居中；userinfo那一页看着尤其难受

**Comment by PersuesJohnson** [comment]
* 单个网页点击like爱心还是灰色的
* 每个单独页面中有一堆的TEXTINGTEXTINGTEXTINGTEXTINGTEXTING
* (不一定算bug)邮箱地址要不要处理筛选一下?
* competitionlist lecturelist 搜索得到的list和tag得到的list都有一些有文字超出的迹象,比如http://183.172.98.151:8080/tag/%E6%9D%90%E6%96%99/
* 搜索的list上面的那些tag似乎有一些长度过长,最右边的物理那个tag被切了一半

**Comment by ritou11** [comment]
recommend_list函数的返回值，第一个为结果列表，包含不超过最大长度的项；第二个为所有可能的结果的数量，用于控制翻页器。不应简单的return result_list, len(result_list)
@thuallen
